"contains csv file indices"
ROWS_PARP = 23

PARP_ID = "wpcf7cfpdf_hidden_reference"
PARP_REGISTER_DATE = "submit_time"
PARP_FIRST_NAME = "Vorname"
PARP_LAST_NAME = "Nachname"
PARP_STREET = "StrasseHausnummer"
PARP_ZIP_CODE = "Postleitzahl"
PARP_VILLAGE = "Ort"
PARP_MAIL = "Mail"
PARP_BIRTHDATE = "Geburtsdatum"
PARP_PHONE = "Telefon"
PARP_EMERCENCY_CONTACT = "Ansprechpartner"
PARP_EMERCENCY_PHONE = "TelefonAnsprechpartner"
PARP_REDUCED = "Ermaessigt"
PARP_VEGETARIAN = "Vegetarisch"
PARP_NEWSLETTER = "Newsletter"
PARP_FRIEND1 = "Person1"
PARP_FRIEND2 = "Person2"
PARP_OTHER = "Sonstiges"
PARP_PHOTO_ALLOWED = "Foto"
PARP_PACKING_LIST = "Packliste"

LEAD_JOB = "Aufgabe"
LEAD_LAST_NAME = "Name"
LEAD_FIRST_NAME = "Vorname"
LEAD_STREET = "Straße"
LEAD_ZIP_CODE = "PLZ"
LEAD_VILLAGE = "Ort"
LEAD_HANDY = "Handy"
LEAD_MAIL = "E-Mail"
LEAD_BIRTHDATE = "Geb."
LEAD_TENT = "Zelt"
LEAD_TEAM = "Team"
LEAD_HAIJK = "Haijk"
LEAD_COMMENT = "Kommentar"
