"contains csv file indices"
ROWS_PARP = 24

PARP_ID = 0
PARP_REGISTER_DATE = 1
PARP_FIRST_NAME = 3
PARP_LAST_NAME = 4
PARP_STREET = 5
PARP_ZIP_CODE = 6
PARP_VILLAGE = 7
PARP_MAIL = 8
PARP_BIRTHDATE = 9
PARP_PHONE = 10
PARP_EMERCENCY_CONTACT = 11
PARP_EMERCENCY_PHONE = 12
PARP_REDUCED = 13
PARP_VEGETARIAN = 14
PARP_NEWSLETTER = 15
PARP_FRIEND1 = 16
PARP_FRIEND2 = 17
PARP_OTHER = 18
PARP_PHOTO_ALLOWED = 19

LEAD_JOB = 0
LEAD_LAST_NAME = 1
LEAD_FIRST_NAME = 2
LEAD_STREET = 3
LEAD_ZIP_CODE = 4
LEAD_VILLAGE = 5
LEAD_PHONE = 6
LEAD_HANDY = 7
LEAD_MAIL = 8
LEAD_BIRTHDATE = 9
LEAD_TENT = 10
LEAD_TEAM = 11
LEAD_COMMENT = 12
