"contains csv file indices"
IDX_PARP_FIRST_NAME = 3
IDX_PARP_LAST_NAME = 4
IDX_PARP_STREET = 5
IDX_PARP_ZIP_CODE = 6
IDX_PARP_VILLAGE = 7
IDX_PARP_MAIL = 8
IDX_PARP_BIRTHDATE = 9
IDX_PARP_PHONE = 10
IDX_PARP_EMERCENCY_CONTACT = 11
IDX_PARP_EMERCENCY_PHONE = 12
IDX_PARP_REDUCED = 13
IDX_PARP_VEGETARIAN = 14
IDX_PARP_NEWSLETTER = 15
IDX_PARP_FRIEND1 = 16
IDX_PARP_FRIEND2 = 17
IDX_PARP_OTHER = 18
IDX_PARP_PHOTO_ALLOWED = 19


IDX_LEAD_JOB = 0
IDX_LEAD_LAST_NAME = 1
IDX_LEAD_FIRST_NAME = 2
IDX_LEAD_STREET = 3
IDX_LEAD_ZIP_CODE = 4
IDX_LEAD_VILLAGE = 5
IDX_LEAD_PHONE = 6
IDX_LEAD_HANDY = 7
IDX_LEAD_MAIL = 8
IDX_LEAD_BIRTHDATE = 9
IDX_LEAD_TENT = 10
IDX_LEAD_TEAM = 11
IDX_LEAD_COMMENT = 12
