"""containes file pathes"""
INPUT_FILE_PATH = r"..\\input\\"
INPUT_FILE_NAME = "2023_teilnehmer_input.csv"
INPUT_TENT_LEADER_FILE_NAME = "2023_leitungsteam_anfrage.csv"
INPUT_REVISION_FILE_NAME = "revisions.txt"
INPUT_TENT_NUMBERS_FILE_NAME = "tent_numbers.txt"
INPUT_PAID_FILE_NAME = "paid.txt"
INPUT_CONFIG_FILE_NAME = "config.txt"
INPUT_LAST_YEAR_FILE_NAME = "2022_zl_tn_out.csv"

PARICIPANT = INPUT_FILE_PATH + INPUT_FILE_NAME
TENT_LEADER = INPUT_FILE_PATH + INPUT_TENT_LEADER_FILE_NAME
REVISION = INPUT_FILE_PATH + INPUT_REVISION_FILE_NAME
TENT_NUMBERS = INPUT_FILE_PATH + INPUT_TENT_NUMBERS_FILE_NAME
PAID = INPUT_FILE_PATH + INPUT_PAID_FILE_NAME
CONFIG = INPUT_FILE_PATH + INPUT_CONFIG_FILE_NAME
LAST_YEAR = INPUT_FILE_PATH + INPUT_LAST_YEAR_FILE_NAME


OUTPUT_DIR_PATH = r"..\\output\\"
OUTPUT_DIR_LISTS = OUTPUT_DIR_PATH+"\\lists\\"
SPECIAL_LISTS = OUTPUT_DIR_LISTS + "\\Special\\"
GESAMT_LISTS = OUTPUT_DIR_LISTS + "\\Gesamt\\"

LIST_TEMPLATE_DIR = "..\\list_templates\\"
